# for linux
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  # LLD linker
  # You may need to install it:
  # - Ubuntu: `sudo apt-get install lld clang`
  # - Fedora: `sudo dnf install lld clang`
  # - Arch: `sudo pacman -S lld clang`
  # "-Clink-arg=-fuse-ld=lld",

  # Mold linker
  # You may need to install it:
  # - Ubuntu: `sudo apt-get install mold clang`
  # - Fedora: `sudo dnf install mold clang`
  # - Arch: `sudo pacman -S mold clang`
  "-Clink-arg=-fuse-ld=/usr/bin/mold",

  # Nightly
  "-Zshare-generics=y",
  "-Zthreads=0",
]


#for Windows
[target.x86_64-pc-windows-msvc]
# LLD linker
# You may need to install it:
# ```
# cargo install -f cargo-binutils
# rustup component add llvm-tools
# ```
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = [
  # Nightly
  # "-Zshare-generics=n", # This needs to be off if you use dynamic linking on Windows.
  # "-Zthreads=0",
]
